### ISSUE TITLE
jp: 🏠 3: Setup Visual Studio Code the Right Way for Vue (beginner)

### ISSUE THREAD

**Issue by ryamakuchi** [ryamakuchi/vv-docs-translation-projects#7]
ref: https://github.com/FrontEndFoxes/docs/blob/master/workshops/vue/nanos/nano3.md

## Check

- [x] ファイルの文言はすべて翻訳されているか
- [x] レビューは完了しているか

**Comment by chisaco** [comment]
私やります！

**Comment by ryamakuchi** [comment]
https://workshops.vuevixens.org/jp/workshops/vue/nanos/nano3.html

おつかれさまでした！！！ 🎉

**Comment by chisaco** [comment]
ありがとうございました！楽しかったです ❤️
